### ISSUE TITLE
missing leda_python

### ISSUE THREAD

**Issue by zylan29** [aliyun/linkedge-thing-access-sdk-python#1]
```
>>> import lethingaccesssdk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/lethingaccesssdk-1.0-py3.5.egg/lethingaccesssdk/__init__.py", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/lethingaccesssdk-1.0-py3.5.egg/lethingaccesssdk/thing_access.py", line 4, in <module>
ImportError: No module named 'leda_python'
```

I have searched for a while, but nowhere to find such `leda_python` module, is it publicly accessable?

**Comment by zylan29** [comment]
Anyone maintaining this repo?

**Comment by back1127** [comment]
It can't run this module in your local. it should run in the link iot edge. please refer to readme file or https://help.aliyun.com/document_detail/88584.html?spm=a2c4g.11186623.6.565.13003265ZmBn00

**Comment by wardenlym** [comment]
为什么不能？原因是需要什么才能运行？我们需要提供详细的说明或者用于模拟的venv环境来进行测试。
